
# 09월 10일 평가 

# 자동차 정보 테이블	
CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(50) NOT NULL
	, PRICE INT NOT NULL
	, BRAND VARCHAR(20) NOT NULL
);

SELECT * FROM car_info;
SELECT * FROM sales_info;

# 자동차 판매 정보 테이블
CREATE TABLE SALES_INFO (
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BUYER_NAME VARCHAR(20) NOT NULL
	, BUYER_TEL VARCHAR(20)  # 010-1111-2222
	, COLOR VARCHAR(30) NOT NULL
	, SALE_DATE DATETIME DEFAULT SYSDATE()
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM)
);

SELECT SALES_NUM 
	, BUYER_NAME
	, IFNULL(BUYER_TEL,'-')
	, SALE_DATE
	, COLOR
	, MODEL_NAME
	, PRICE
FROM sales_info S INNER JOIN car_info C
ON S.MODEL_NUM = C.MODEL_NUM
ORDER BY SALE_DATE DESC;
	





