
# 09월 10일 평가 

# 자동차 정보 테이블
CREATE TABLE CAR_INFO (
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(50) NOT NULL
	, PRICE INT NOT NULL
	, BRAND VARCHAR(20) NOT NULL
);

SELECT * FROM CAR_INFO;
SELECT * FROM SALES_INFO;

# 자동차 판매 정보 테이블
CREATE TABLE SALES_INFO (
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BUYER_NAME VARCHAR(20) NOT NULL
	, BUYER_TEL VARCHAR(20) # 010-1111-2222
	, COLOR VARCHAR(30) NOT NULL
	, SALE_DATE DATETIME DEFAULT SYSDATE()
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM)
);