
#게시판 프로젝트 테이블
CREATE TABLE board (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM board;

INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('hello', '임꺽정', '내용5', 7);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('제목입니다', '홍길동', '내용4', 2);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('title', 'java', '내용3', 1);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('두 번째 글', 'kimjava', '내용2', 2);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('첫 번째 글', '김자바', '내용1', 7);
COMMIT;

