
#게시판 프로젝트 테이블

CREATE TABLE board (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM board;

INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('hello', '임꺽정', '내용5', 7);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('제목입니다', '홍길동', '내용4', 2);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('title', 'java', '내용3', 1);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('두 번째 글', 'kimjava', '내용2', 2);
INSERT INTO board(TITLE, WRITER, CONTENT, READ_CNT) 
VALUES('첫 번째 글', '김자바', '내용1', 7);
COMMIT;




#--------------------------------------------------------------#

#상품 정보 테이블

CREATE TABLE ITEM(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_CATEGORY VARCHAR(30) NOT NULL
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(50)
	, ITEM_STATUS VARCHAR(10) #상품준비중, 판매중, 매진
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM ITEM;

INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE,ITEM_INTRO, ITEM_STATUS) 
VALUES ('상의', '상의1', 10000, '상의1입니다', '판매중');
INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE,ITEM_INTRO, ITEM_STATUS) 
VALUES ('하의', '하의1', 15000, '하의1입니다', '매진');
INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE,ITEM_INTRO, ITEM_STATUS) 
VALUES ('신발', '신발1', 20000, '신발1입니다', '상품준비중');
COMMIT;

SELECT SUM(ITEM_PRICE) FROM item; 
# SUM() : 괄호 안에 있는 컬럼의 합을 구해줌





