
# 도서 쇼핑몰 프로젝트 테이블

# 1. 회원 테이블
# 2. 도서 카테고리 테이블
# 3. 도서 정보 테이블 
# 4. 구매 테이블
# 5. 장바구니 테이블


# 1. 회원 테이블
CREATE TABLE SHOP_MEMBER (
	MEM_ID VARCHAR(20) PRIMARY KEY
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_TEL VARCHAR(20)     # 010-1111-2222
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(50)
	, MEM_EMAIL VARCHAR(50) UNIQUE
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_ROLE VARCHAR(10) NOT NULL DEFAULT 'USER'  # 관리자 : ADMIN, 일반 고객 : USER
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM shop_member;

SELECT MEM_ID
FROM shop_member
WHERE MEM_ID = 'java';

UPDATE shop_member
SET 
	MEM_PW = '1111'
	, MEM_ROLE = 'ADMIN'
WHERE MEM_ID = 'admin'; 
COMMIT;


# 2. 도서 카테고리 테이블
CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO BOOK_CATEGORY VALUES (1, '소설');
INSERT INTO BOOK_CATEGORY VALUES (2, '인터넷/IT');
INSERT INTO BOOK_CATEGORY VALUES (3, '자기계발');
COMMIT;

SELECT * FROM BOOK_CATEGORY;


# 3. 도서 정보 테이블 
CREATE TABLE book (
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(20) NOT NULL
	, PUBLISHER VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE()  # 쇼핑몰에 상품 등록한 날짜
	, BOOK_INTRO VARCHAR(50)
	, CATE_NUM INT REFERENCES BOOK_CATEGORY(CATE_NUM)
); 

SELECT * FROM book;

COMMIT;


# 4. 장바구니 테이블
CREATE TABLE SHOP_CART (
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT
		, BOOK_NUM INT REFERENCES book(BOOK_NUM)
		, CART_CNT INT NOT NULL # 장바구니에 담은 도서 수량
		, MEM_ID VARCHAR(20) REFERENCES shop_member(MEM_ID)
		, TOTAL_PRICE INT NOT NULL
		, CART_DATE DATETIME DEFAULT SYSDATE()
); 

SELECT * FROM shop_cart;

INSERT INTO shop_cart (BOOK_NUM
	, CART_CNT
	, MEM_ID
	, TOTAL_PRICE
	) 
VALUES (
	27
	, 2
	, 
	'user'
	, (SELECT PRICE
		FROM BOOK
		WHERE BOOK_NUM = 27) * 3
	);

# 장바구니에 저장된 상품명, 가격, 수량, 총가격, 등록일 조회
SELECT CART_NUM
	, CART_CNT
	, TOTAL_PRICE
	, CART_DATE
	, TITLE
	, PRICE
	, C.BOOK_NUM
FROM shop_cart C INNER JOIN book B
ON C.BOOK_NUM = B.BOOK_NUM
WHERE MEM_ID = 'user'
ORDER BY CART_DATE DESC;





