SELECT * FROM MY_MEMBER;

# 1번
CREATE TABLE MY_MEMBER(
	MEM_NUM INT PRIMARY KEY,
	MEM_ID VARCHAR(20) NOT NULL,
	MEM_PW VARCHAR(20) NOT NULL,
	MEM_NAME VARCHAR(10) NOT NULL,
	MEM_AGE INT,
	MEM_EMAIL VARCHAR(20) UNIQUE
);

# 2번 
INSERT INTO MY_MEMBER 
VALUES (101, 'kim', '1234', '김자바', 30, 'kim@gmail.com');
INSERT INTO MY_MEMBER 
VALUES (102, 'hong', '5678', '홍자바', 25, 'hong@gmail.com');

# 3번
UPDATE MY_MEMBER
SET
	MEM_NAME = '유관순',
	MEM_AGE = MEM_AGE + 5
WHERE MEM_NUM = 101;

# 4번
SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE (SAL >= 500 AND SAL <= 3000) AND COMM IS NOT NULL; 

SELECT * FROM emp;

# 5번
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기' OR  ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

# 6번
SELECT 
	EMPNO, 
	ENAME, 
	DEPTNO,
	CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부' END 부서명
FROM emp;

# 7번
SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0)
FROM emp
WHERE MONTH(HIREDATE) = 1
ORDER BY HIREDATE;

