
CREATE TABLE BASIC_BOARD (
 BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT  
 , TITLE VARCHAR(30)
 , WRITER VARCHAR(20)
 , CONTENT VARCHAR(50)
 , READ_CNT INT DEFAULT 0
 , CREATE_DATE DATETIME DEFAULT SYSDATE()
 );
 
SELECT * FROM BASIC_BOARD;
 
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목1', '작성자1', '내용1');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목2', '작성자2', '내용2');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목3', '작성자3', '내용3');
COMMIT;

# 데이터에 변화가 생기는 쿼리문(insert, delete, update)을 실행하면 commit or rollback;




# 회원 정보 테이블
CREATE TABLE BASIC_MEMBER(
	MEM_ID VARCHAR(20) PRIMARY KEY,
	MEM_PW VARCHAR(20) NOT NULL,
	MEM_NAME VARCHAR(10),
	MEM_AGE INT,
	BIRTHDAY DATETIME
);

SELECT * FROM BASIC_MEMBER;

INSERT INTO BASIC_MEMBER 
VALUES ('hong', '1234', '홍길동', 20, '1999-05-07');
INSERT INTO BASIC_MEMBER
VALUES ('gogo', '4321', '고길동', 30, '1987-07-08');
COMMIT;


SELECT MEM_NAME
FROM basic_member
WHERE MEM_ID = 'java';


# 게시글 목록 페이지2 문제 자바에 작성할 쿼리
SELECT BOARD_NUM
      , TITLE
      , WRITER
      , CREATE_DATE
      , READ_CNT
FROM BASIC_BOARD
WHERE TITLE LIKE '%리%';










