# 모든 ip 접근 허용(단, 강의실 밖에서는 안됨)
GRANT ALL PRIVILEGES ON TEAM_DB.* TO 'pdy'@'%' IDENTIFIED BY 'mariadb';
GRANT ALL PRIVILEGES ON TEAM_DB.* TO 'psh'@'%' IDENTIFIED BY 'mariadb';
GRANT ALL PRIVILEGES ON TEAM_DB.* TO 'rasberry'@'%' IDENTIFIED BY 'mariadb';


CREATE TABLE member2 (
	ID VARCHAR(50) PRIMARY KEY,
	PW VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL
);

ALTER TABLE member2 
ADD COLUMN ROLE VARCHAR(20) DEFAULT 'USER';

SELECT * FROM member2;

SELECT * FROM board;

CREATE TABLE SECURITY_MEMBER (
	MEM_EMAIL VARCHAR(100) PRIMARY KEY
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL DEFAULT 'USER' # 'MANAGER', 'ADMIN'
);

SELECT * FROM security_member;


