SELECT * FROM FARM_STATUS;

SELECT * FROM CHICKEN_FARM;

SELECT * FROM chicken;

SELECT * FROM CHICKEN_BATCH;

SELECT * FROM DANGER_NOTICE;

SELECT * FROM farm_management;

SELECT * FROM MEMBER;

SELECT * FROM NOTE;

SELECT * FROM chicken_weight_history;

SELECT * FROM chicken_inoculation_history;

INSERT INTO chicken_farm VALUES (1, '1번 양계장');


# 배치 번호 생성
SELECT CONCAT(
   YEAR(NOW()),
   '-',
   LPAD(IFNULL(MAX(CONVERT(SUBSTRING(BATCH_ID, 6), UNSIGNED)), 0) + 1, 3, '0')
)
FROM CHICKEN_BATCH
WHERE BATCH_ID LIKE CONCAT(YEAR(NOW()), '-%');


# 자정 기준으로 나이 한 살 증가, 나이에 따른 성장 단계 자동 지정
UPDATE CHICKEN C INNER JOIN CHICKEN_BATCH B
ON C.BATCH_ID = B.BATCH_ID
SET
   C.AGE = DATEDIFF(CURRENT_DATE(), B.ENTRY_DATE) + 1,
   C.GROWTH_STAGE =
       CASE
           WHEN DATEDIFF(CURRENT_DATE(), B.ENTRY_DATE) + 1 BETWEEN 1 AND 14 THEN 'CHICK'
           WHEN DATEDIFF(CURRENT_DATE(), B.ENTRY_DATE) + 1 BETWEEN 15 AND 28 THEN 'GROWER'
           WHEN DATEDIFF(CURRENT_DATE(), B.ENTRY_DATE) + 1 > 28 THEN 'FINISHER'
           ELSE C.GROWTH_STAGE 
			  # 어떤 조건에도 맞지 않는다면 C.GROWTH_STAGE 기존 값 유지
			  # (데이터 무결성을 위해 안전장치 추가)
       END;

INSERT INTO chicken_inoculation (CHICKEN_ID) VALUES (1);

