SELECT * FROM FARM_STATUS;

SELECT * FROM CHICKEN_FARM;

SELECT * FROM CHICKEN;

SELECT * FROM CHICKEN_BATCH;

SELECT * FROM DANGER_NOTICE;

SELECT * FROM management;

SELECT * FROM MEMBER;

SELECT * FROM NOTE;

SELECT * FROM CHICKEN_WEIGHT_HISTORY;

INSERT INTO chicken_farm VALUES (1, '1번 양계장');

INSERT INTO CHICKEN_BATCH (BATCH_ID, ENTRY_DATE, INITIAL_COUNT, CURRENT_COUNT, FARM_NUM)
VALUES (
    (SELECT CONCAT(YEAR(NOW()), '-', LPAD(IFNULL(MAX(SUBSTRING(BATCH_ID, 6)), 0) + 1, 3, '0'))
     FROM CHICKEN_BATCH 
     WHERE BATCH_ID LIKE CONCAT(YEAR(NOW()), '-%')),
    '2025-09-30',
    10,
    10,
    1
);