SELECT * FROM TEST_TABLE;

CREATE TABLE TEST_TABLE (
	NUM INT PRIMARY KEY
	, NAME VARCHAR(20)
);

SELECT TEMP_DATA, REC_TIME FROM th_sensor ORDER BY th_sensor_id DESC;

SELECT rec_time, NO2_DATA, CO_DATA, CO2_DATA, NH3_DATA FROM th_sensor ORDER BY th_sensor_id DESC;

ALTER TABLE TH_SENSOR
ADD COLUMN NO2_DATA FLOAT NOT NULL DEFAULT 0,
ADD COLUMN CO_DATA FLOAT NOT NULL DEFAULT 0,
ADD COLUMN CO2_DATA FLOAT NOT NULL DEFAULT 0,
ADD COLUMN NH3_DATA FLOAT NOT NULL DEFAULT 0;
